# Exercises

There are three exercises in this notebook:

1. Use the cross-validation method to test the linear regression with different $\alpha$ values, at least three.
2. Implement a SGD method that will train the Lasso regression for 10 epochs.
3. Extend the Fisher's classifier to work with two features. Use the class as the $y$.

## 1. Cross-validation linear regression

You need to change the variable ``alpha`` to be a list of alphas. Next do a loop and finally compare the results.

In [2]:
import numpy as np
import pandas as pd

In [9]:
x = np.array([188, 181, 197, 168, 167, 187, 178, 194, 140, 176, 168, 192, 173, 142, 176]).reshape(-1, 1).reshape(15,1)
y = np.array([141, 106, 149, 59, 79, 136, 65, 136, 52, 87, 115, 140, 82, 69, 121]).reshape(-1, 1).reshape(15,1)

x = np.asmatrix(np.c_[np.ones((15,1)),x])

I = np.identity(2)
alphas = [x * 0.1 for x in range(-10, 11)] # change here
results = []
# add 1-3 line of code here
for alpha in alphas:
    w = np.linalg.inv(x.T*x + alpha * I)*x.T*y
    w=w.ravel()
    results.append([alpha, w.item(0), w.item(1)])

# add 1-3 lines to compare the results
summary = pd.DataFrame(data=results, columns=["alpha", "w1", "w2"])
summary

    alpha          w1        w2
0    -1.0   26.667097  0.442962
1    -0.9   30.122934  0.423398
2    -0.8   34.607973  0.398008
3    -0.7   40.662425  0.363733
4    -0.6   49.284735  0.314922
5    -0.5   62.548230  0.239837
6    -0.4   85.580223  0.109451
7    -0.3  135.462841 -0.172936
8    -0.2  324.767138 -1.244596
9    -0.1 -817.017374  5.219094
10    0.0 -180.924018  1.618142
11    0.1 -101.723971  1.169788
12    0.2  -70.751422  0.994451
13    0.3  -54.237043  0.900962
14    0.4  -43.972861  0.842856
15    0.5  -36.975220  0.803242
16    0.6  -31.898837  0.774504
17    0.7  -28.047977  0.752704
18    0.8  -25.026648  0.735600
19    0.9  -22.592872  0.721822
20    1.0  -20.590447  0.710486

## 2. Implement based on the Ridge regression example, the Lasso regression.

Please implement the SGD method and compare the results with the sklearn Lasso regression results.

In [ ]:
def sgd():
    # your code goes here
    pass

In [ ]:
x = np.array([188, 181, 197, 168, 167, 187, 178, 194, 140, 176, 168, 192, 173, 142, 176]).reshape(-1, 1).reshape(15,1)
y = np.array([141, 106, 149, 59, 79, 136, 65, 136, 52, 87, 115, 140, 82, 69, 121]).reshape(-1, 1).reshape(15,1)

x = np.asmatrix(np.c_[np.ones((15,1)),x])

I = np.identity(2)
alpha = 0.1 


w = np.linalg.inv(x.T*x + alpha * I)*x.T*y # update this line
w=w.ravel()

## 3. Extend the Fisher's classifier

Please extend the targets of the ``iris_data`` variable and use it as the $y$.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

iris_data = load_iris()
iris_df = pd.DataFrame(iris_data.data,columns=iris_data.feature_names)
iris_df.head()

x = iris_df['sepal width (cm)'].values # change here
y = iris_df['sepal length (cm)'].values # change here

dataset_size = np.size(x)

mean_x, mean_y = np.mean(x), np.mean(y)

SS_xy = np.sum(y * x) - dataset_size * mean_y * mean_x
SS_xx = np.sum(x * x) - dataset_size * mean_x * mean_x

a = SS_xy / SS_xx
b = mean_y - a * mean_x


y_pred = a * x + b